spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev #开发环境
  application:
    name: myspringcloud-config-dev

---

spring:
  profiles: test #测试环境
  application:
    name: myspringcloud-config-test

#保存为UTF-8格式，否则上传到git乱码